variable "elb_sgs" {}
variable "public_subnets" {}
variable "domain_name" {}
variable "dev_instance_type" {}
variable "dev_ami" {}
variable "elb_healthy_threshold" {}
variable "elb_unhealthy_threshold" {}
variable "elb_timeout" {}
variable "elb_interval" {} 
variable "lc_instance_type" {}
variable "asg_max" {}
variable "asg_min" {}
variable "asg_grace" {}
variable "asg_hct" {}
variable "asg_cap" {}
variable "key_name" {}
variable "vpc_security_group_ids" {}
variable "iam_instance_profile" {}
variable "subnet_id" {}
variable "s3_code_bucket" {}
variable "vpc_private_sg_ids" {}
variable "vpc_private_subnet_ids" {}